services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql

